matrix:
  include:
    - language: python
      python: 3.6
      before_install:
        - cd ws1_restful_autoverleih
      install:
        - pip install -r requirements.txt
      script:
        - pytest
        
    - language: csharp
      solution: ./ws2_soap_waehrungsrechner/WSCurrencyConverter/WSCurrencyConverter.sln
      before_install:
        - cd ws2_soap_waehrungsrechner/WSCurrencyConverter/CurrencyConverterService
      install:
        -
      script:
        -
