matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd ws1_restful_autoverleih
      install:
        - pip install -r .requirements.txt
      script:
        - python ./tests/autoverleih_tests.py test
    - language: csharp
      before_script:
        - cd .ws2_soap_waehrungsrechner/WSCurrencyConverter
      solution: WSCurrencyConverter.sln
