"""empty message

Revision ID: 05a0fb418234
Revises: 50985ada54fb
Create Date: 2018-04-01 14:27:30.440304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a0fb418234'
down_revision = '50985ada54fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('image_file_name', sa.String(length=140), nullable=True))
    op.drop_column('car', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('image_path', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('car', 'image_file_name')
    # ### end Alembic commands ###
