"""empty message

Revision ID: 4a374a8a964a
Revises: a4fecc872301
Create Date: 2018-03-27 19:19:38.264774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a374a8a964a'
down_revision = 'a4fecc872301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_history', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_history', 'total_price')
    # ### end Alembic commands ###
