"""empty message

Revision ID: 50985ada54fb
Revises: 
Create Date: 2018-04-01 14:12:40.717722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50985ada54fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('image_path', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'image_path')
    # ### end Alembic commands ###
