"""empty message

Revision ID: 9ede99622fc2
Revises: e89a96cf6ee5
Create Date: 2018-03-29 00:12:39.712782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ede99622fc2'
down_revision = 'e89a96cf6ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('rented', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'rented')
    # ### end Alembic commands ###
