"""empty message

Revision ID: e89a96cf6ee5
Revises: 994b12e3be15
Create Date: 2018-03-28 22:55:35.435383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89a96cf6ee5'
down_revision = '994b12e3be15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('car', sa.Column('gps_lat', sa.Float(), nullable=True))
    op.add_column('car', sa.Column('gps_long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'gps_long')
    op.drop_column('car', 'gps_lat')
    op.drop_column('car', 'color')
    # ### end Alembic commands ###
